print logs in docker test

diff --git a/.github/workflows/test-docker.yml b/.github/workflows/test-docker.yml
--- a/.github/workflows/test-docker.yml
+++ b/.github/workflows/test-docker.yml
@@ -34,4 +34,17 @@ jobs:
         docker ps
     - name: check if the web server is running
       run: |
-        curl -s http://localhost:8785
+        run: |
+          curl -s -o /dev/null -w "%{http_code}" http://localhost:8765
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8765)
+        if [[ $status_code -ne 200 ]]; then
+            echo "Request failed with status code:"
+            echo ${status_code}
+            exit 1
+        fi
+    - name: failed tests 🚩
+        working-directory: tests
+        if: ${{ failure() }}
+        run: |
+          echo "check docker logs"
+          docker compose -f logs
